FROM node:22

WORKDIR /app

# Instala Dependências no Node
COPY package.json package-lock.json ./
RUN npm ci

#COPY . .

COPY tsconfig.json ./
COPY src ./src

#Build aplicação
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]